### ISSUE TITLE
help with running gflownet.py

### ISSUE THREAD

**Issue by HartejSoin** [bengioe/gflownet#13]
I've just started with gflownets and wanted to run the code using the default parameter values, however I keep getting exception while sampling, and ultimately, an attribute error with torch_geometric. Where could I be going wrong?

**Comment by bengioe** [comment]
Hi @nimbus2003. In some version of torch_geometric the `__slice__` attribute was changed to `_slice_dict`. This has been fixed in the [subtb](https://github.com/GFNOrg/gflownet/tree/subtb) branch. Alternatively, make sure that the torch_geometric (and related packages) version that you install matches that of the `requirements.txt` file.
